### ISSUE TITLE
Need a verified, up-to-date Hammer setup guide in the README

### ISSUE THREAD

**Issue by squeek502** [fortressforever/fortressforever-maps#1]
Some possibly useful references:
- http://forums.fortress-forever.com/showpost.php?p=500307&postcount=51 (might be outdated due to Steampipe)
- http://forums.fortress-forever.com/showpost.php?p=502690&postcount=62
- http://forums.fortress-forever.com/showpost.php?p=502693&postcount=63

**Comment by R00Ki3** [comment]
I could try to set this up. You want it set up to use the current ff steam beta? you want me to use the online wiki with pictures? or an html file? or what?

**Comment by squeek502** [comment]
Not sure. Anywhere is good for now, and then we can have it mirrored (or linked) where ever it's relevant.

It should be from the perspective of a brand new Steam install with zero other games installed. Also, it should be for the Steam version of the game rather than the /sourcemods/ version.

I've installed a fresh Windows 7 VM for testing, and will try a few setups to see what works.

**Comment by R00Ki3** [comment]
Sounds like a good idea with the VM. I'll do the same.
